export const BUBBLE_STYLES = {
  SQUARE: 'square',
  ROUNDED: 'rounded',
};

const DEFAULT_BUBBLE_HEIGHT = 70;
const DEFAULT_LANGUAGE_CODE = 'en';
const DEFAULT_TITLE = 'Untitled Project';

const DESCRIPTION = 'description';
const TITLE = 'title';
const LOADED_JSON = 'loadedJson';
const BUBBLE_STYLE = 'bubblesStyle';
const BLACK_N_WHITE = 'blackAndWhite';
const SHOW_TIMES = 'showTimes';
const AUTO_SCALE_HEIGHT = 'autoScaleHeightOnResize';
const START_PLAYING_WHEN_BUBBLES_CLICKED = 'startPlayingWhenBubbleIsClicked';
const STOP_PLAYING_END_OF_SECTION = 'stopPlayingAtTheEndOfSection';
const BUBBLE_HEIGHT = 'bubbleHeight';
const LANGUAGE = 'language';

export const PROJECT = {
  DESCRIPTION,
  TITLE,
  LOADED_JSON,
  BUBBLE_STYLE,
  BLACK_N_WHITE,
  SHOW_TIMES,
  AUTO_SCALE_HEIGHT,
  START_PLAYING_WHEN_BUBBLES_CLICKED,
  STOP_PLAYING_END_OF_SECTION,
  BUBBLE_HEIGHT,
  LANGUAGE,
};

export const RDF_NAMESPACE = 'tl';

export const PROJECT_SETTINGS_KEYS = [
  BUBBLE_STYLE,
  BLACK_N_WHITE,
  SHOW_TIMES,
  AUTO_SCALE_HEIGHT,
  START_PLAYING_WHEN_BUBBLES_CLICKED,
  STOP_PLAYING_END_OF_SECTION,
  BUBBLE_HEIGHT,
];

export const SETTINGS_ATTRIBUTE = `${RDF_NAMESPACE}:settings`;

export const DEFAULT_SETTINGS = {
  [BUBBLE_HEIGHT]: DEFAULT_BUBBLE_HEIGHT,
  [SHOW_TIMES]: false,
  [BLACK_N_WHITE]: false,
  [BUBBLE_STYLE]: BUBBLE_STYLES.ROUNDED,
  [AUTO_SCALE_HEIGHT]: true,
  [START_PLAYING_WHEN_BUBBLES_CLICKED]: true,
  [STOP_PLAYING_END_OF_SECTION]: false,
};

export const DEFAULT_PROJECT_STATE = {
  ...DEFAULT_SETTINGS,
  [LANGUAGE]: DEFAULT_LANGUAGE_CODE,
  [TITLE]: DEFAULT_TITLE,
  [DESCRIPTION]: '',
  [LOADED_JSON]: {},
};

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const RESET_DOCUMENT = 'RESET_DOCUMENT';
export const EXPORT_DOCUMENT = 'EXPORT_DOCUMENT';
export const IMPORT_DOCUMENT = 'IMPORT_DOCUMENT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
