const DEFAULT_RANGES_STATE = {};

const SPLIT_RANGE_AT = 'SPLIT_RANGE_AT';
const GROUP_RANGES = 'GROUP_RANGES';
const ON_SELECT_RANGE = 'ON_SELECT_RANGE';
const UPDATE_RANGE = 'UPDATE_RANGE';
const MOVE_POINT = 'MOVE_POINT';
const DELETE_RAGE = 'DELETE_RAGE';

export default {
  DEFAULT_RANGES_STATE,
  SPLIT_RANGE_AT,
  GROUP_RANGES,
  ON_SELECT_RANGE,
  UPDATE_RANGE,
  MOVE_POINT,
  DELETE_RAGE,
};
