const DEFAULT_VIEWSTATE_STATE = {
  isPlaying: false,
  currentTime: 0,
  zoom: 1.0,
  x: 0,
  isImportOpen: false,
  isSettingsOpen: false,
  volume: 70,
};

const PLAY_AUDIO = 'PLAY_AUDIO';
const STOP_AUDIO = 'STOP_AUDIO';
const UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME';
const ZOOM_IN = 'ZOOM_IN';
const ZOOM_OUT = 'ZOOM_OUT';
const RESET_ZOOM = 'RESET_ZOOM';
const PAN_TO_POSITION = 'PAN_TO_POSITION';
const SHOW_IMPORT_MODAL = 'SHOW_IMPORT_MODAL';
const DISMISS_IMPORT_MODAL = 'DISMISS_IMPORT_MODAL';
const SHOW_SETTINGS_MODAL = 'SHOW_SETTINGS_MODAL';
const DISMISS_SETTINGS_MODAL = 'DISMISS_SETTINGS_MODAL';
const NEXT_BUBBLE = 'NEXT_BUBBLE';
const PREVIOUS_BUBBLE = 'PREVIOUS_BUBBLE';
const FAST_FORWARD = 'FAST_FORWARD';
const FAST_REWARD = 'FAST_REWARD';

export default {
  DEFAULT_VIEWSTATE_STATE,
  PLAY_AUDIO,
  STOP_AUDIO,
  UPDATE_CURRENT_TIME,
  ZOOM_IN,
  ZOOM_OUT,
  RESET_ZOOM,
  PAN_TO_POSITION,
  SHOW_IMPORT_MODAL,
  DISMISS_IMPORT_MODAL,
  SHOW_SETTINGS_MODAL,
  DISMISS_SETTINGS_MODAL,
  NEXT_BUBBLE,
  PREVIOUS_BUBBLE,
  FAST_FORWARD,
  FAST_REWARD,
  SET_VOLUME,
};
