module.exports = {
  viewState: {
    runTime: 182282,
    isPlaying: false,
    currentTime: 104140.04051863858,
    zoom: 1,
    x: 0,
    isImportOpen: false,
    isSettingsOpen: false,
    volume: 70,
    metadataToEdit: null,
    projectMetadataEditorOpen: false,
    source: null,
    verifyDialog: {
      open: false,
      title: '',
    },
  },
  project: {
    bubbleHeight: 55,
    showTimes: false,
    blackAndWhite: false,
    bubblesStyle: 'rounded',
    autoScaleHeightOnResize: false,
    startPlayingWhenBubbleIsClicked: false,
    stopPlayingAtTheEndOfSection: false,
    startPlayingAtEndOfSection: false,
    backgroundColour: '#fff',
    language: 'en',
    title: '',
    description: '',
    loadedJson: {
      label: {
        en: [''],
      },
      summary: {
        en: [''],
      },
      type: 'Manifest',
      id: 'http://digirati.com/iiif/v3/temporary/manifest',
      items: [
        {
          label: {
            en: ['Untitled Item'],
          },
          type: 'Canvas',
          id: 'http://digirati.com/iiif/v3/temporary/canvas/c1',
          items: [
            {
              type: 'AnnotationPage',
              items: [
                {
                  id: 'http://digirati.com/iiif/v3/temporary/annotation/c1-1',
                  type: 'Annotation',
                  motivation: 'painting',
                  label: {
                    en: ['Untitled audio'],
                  },
                  body: {
                    id:
                      'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Loopster.mp3',
                    type: 'Audio',
                    duration: 182.282469,
                  },
                  target: 'http://digirati.com/iiif/v3/temporary/canvas/c',
                },
              ],
              id: 'http://digirati.com/iiif/v3/temporary/list/c1-ap',
            },
          ],
        },
      ],
      structures: [
        {
          id: 'http://digirati.com/iiif/v3/temporary/range/r0',
          type: 'Range',
          label: {
            en: [''],
          },
          items: [
            {
              id:
                'http://digirati.com/iiif/v3/temporary/canvas/c1#t=0,182.282469',
              type: 'Canvas',
            },
          ],
        },
      ],
      'tl:settings': {
        'tl:bubblesStyle': 'rounded',
        'tl:blackAndWhite': false,
        'tl:showTimes': false,
        'tl:autoScaleHeightOnResize': false,
        'tl:startPlayingWhenBubbleIsClicked': true,
        'tl:stopPlayingAtTheEndOfSection': false,
        'tl:startPlayingAtEndOfSection': false,
        'tl:bubbleHeight': 55,
        'tl:backgroundColour': '#fff',
      },
      '@context': [
        'http://digirati.com/ns/timeliner',
        'http://www.w3.org/ns/anno.jsonld',
        'http://iiif.io/api/presentation/3/context.json',
      ],
    },
  },
  canvas: {
    url:
      'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Loopster.mp3',
    isLoaded: true,
    loadingPercent: 100,
    error: {
      code: null,
      description: '',
    },
  },
  range: {
    selected: ['id-1548251126620'],
    list: {
      'http://digirati.com/iiif/v3/temporary/range/r0': {
        id: 'http://digirati.com/iiif/v3/temporary/range/r0',
        label: '',
        summary: '',
        startTime: 0,
        endTime: 73710.46839546191,
        depth: 1,
        colour: '#A63993',
        whiteText: false,
        isSelected: false,
      },
      'id-1548251118755': {
        startTime: 73710.46839546191,
        endTime: 80357.70502431119,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 1,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251118755',
      },
      'id-1548251119272': {
        startTime: 80357.70502431119,
        endTime: 89663.83630470016,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 1,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251119272',
      },
      'id-1548251119906': {
        startTime: 89663.83630470016,
        endTime: 96163.35656401944,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 1,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251119906',
      },
      'id-1548251120469': {
        startTime: 96163.35656401944,
        endTime: 104140.04051863858,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 1,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251120469',
      },
      'id-1548251121033': {
        startTime: 104140.04051863858,
        endTime: 182282.46899999998,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 1,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251121033',
      },
      'id-1548251124459': {
        startTime: 73710.46839546191,
        endTime: 104140.04051863858,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 3,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251124459',
      },
      'id-1548251126620': {
        startTime: 73710.46839546191,
        endTime: 89663.83630470016,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 2,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251126620',
      },
      'id-1548251128847': {
        startTime: 89663.83630470016,
        endTime: 104140.04051863858,
        label: 'Untitled range',
        summary: '',
        colour: null,
        depth: 2,
        isSelected: false,
        whiteText: false,
        id: 'id-1548251128847',
      },
    },
  },
  undoHistory: {
    undoQueue: [],
    redoQueue: [],
  },
  _persist: {
    version: -1,
    rehydrated: true,
  },
};
